services:
  backend:
    image: backend-image
    container_name: backend-container
    ports:
      - "6000:6000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    image: frontend-image 
    container_name: frontend-container
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - backend
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor-aiapp
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-aiapp
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-aiapp
    ports:
      - "3001:3000" 